language: python

os:
  - linux
  - osx

python:
  - "3.6"
  - "3.7"

# safelist
branches:
  only:
  - master

install:
  - pip install flake8
    
script:
  - flake8 *.py

after_success:
  - coveralls