language: python

os:
  - linux
  - osx

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install autopep8 isort yapf
    
script:
  - flake8 --aggressive --aggressive
  - 

after_success:
  - coveralls